---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: omero-database
    image: centos/systemd
    privileged: true
    command: /sbin/init
  - name: omero-server
    image: centos/systemd
    privileged: true
    command: /sbin/init
  - name: omero-web
    image: centos/systemd
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../../playbook.yml
scenario:
  name: centos7
verifier:
  name: testinfra
  directory: ../resources/tests/
